# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import greenness_track_toolkit.rpc.agent_info_service_pb2 as agent__info__service__pb2
import greenness_track_toolkit.rpc.common_pb2 as common__pb2


class AgentInfoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getUniqueEid = channel.unary_unary(
                '/greenness_track_toolkit.rpc.AgentInfoService/getUniqueEid',
                request_serializer=agent__info__service__pb2.EidRequest.SerializeToString,
                response_deserializer=agent__info__service__pb2.EidResponse.FromString,
                )
        self.uploadComputerInfo = channel.unary_unary(
                '/greenness_track_toolkit.rpc.AgentInfoService/uploadComputerInfo',
                request_serializer=agent__info__service__pb2.UploadComputerInfoRequest.SerializeToString,
                response_deserializer=common__pb2.BaseResponse.FromString,
                )
        self.uploadStatus = channel.unary_unary(
                '/greenness_track_toolkit.rpc.AgentInfoService/uploadStatus',
                request_serializer=agent__info__service__pb2.UploadStatusRequest.SerializeToString,
                response_deserializer=common__pb2.BaseResponse.FromString,
                )


class AgentInfoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getUniqueEid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def uploadComputerInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def uploadStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentInfoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getUniqueEid': grpc.unary_unary_rpc_method_handler(
                    servicer.getUniqueEid,
                    request_deserializer=agent__info__service__pb2.EidRequest.FromString,
                    response_serializer=agent__info__service__pb2.EidResponse.SerializeToString,
            ),
            'uploadComputerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.uploadComputerInfo,
                    request_deserializer=agent__info__service__pb2.UploadComputerInfoRequest.FromString,
                    response_serializer=common__pb2.BaseResponse.SerializeToString,
            ),
            'uploadStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.uploadStatus,
                    request_deserializer=agent__info__service__pb2.UploadStatusRequest.FromString,
                    response_serializer=common__pb2.BaseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'greenness_track_toolkit.rpc.AgentInfoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AgentInfoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getUniqueEid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greenness_track_toolkit.rpc.AgentInfoService/getUniqueEid',
            agent__info__service__pb2.EidRequest.SerializeToString,
            agent__info__service__pb2.EidResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def uploadComputerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greenness_track_toolkit.rpc.AgentInfoService/uploadComputerInfo',
            agent__info__service__pb2.UploadComputerInfoRequest.SerializeToString,
            common__pb2.BaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def uploadStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greenness_track_toolkit.rpc.AgentInfoService/uploadStatus',
            agent__info__service__pb2.UploadStatusRequest.SerializeToString,
            common__pb2.BaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
