# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent_info_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import greenness_track_toolkit.rpc.common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61gent_info_service.proto\x12\x1bgreenness_track_toolkit.rpc\x1a\x0c\x63ommon.proto\"a\n\nEidRequest\x12\x1b\n\x13masterAgentHostname\x18\x01 \x01(\t\x12\x10\n\x08isMaster\x18\x02 \x01(\x08\x12\x11\n\townerName\x18\x03 \x01(\t\x12\x11\n\tstartTime\x18\x04 \x01(\t\"\xb8\x01\n\x19UploadComputerInfoRequest\x12\x0b\n\x03\x65id\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_ip\x18\x02 \x01(\t\x12\x10\n\x08\x63puBrand\x18\x03 \x01(\t\x12\x15\n\rcpuKernelNums\x18\x04 \x01(\x05\x12\x10\n\x08\x63puClock\x18\x05 \x01(\t\x12\x10\n\x08gpuBrand\x18\x06 \x01(\t\x12\x0f\n\x07gpuNums\x18\x07 \x01(\x05\x12\x10\n\x08gpuClock\x18\x08 \x01(\t\x12\x0c\n\x04rank\x18\t \x01(\x05\"h\n\x0b\x45idResponse\x12;\n\nresultCode\x18\x01 \x01(\x0e\x32\'.greenness_track_toolkit.rpc.ResultCode\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0b\n\x03\x65id\x18\x03 \x01(\t\"2\n\x13UploadStatusRequest\x12\x0b\n\x03\x65id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2\xdb\x02\n\x10\x41gentInfoService\x12\x61\n\x0cgetUniqueEid\x12\'.greenness_track_toolkit.rpc.EidRequest\x1a(.greenness_track_toolkit.rpc.EidResponse\x12w\n\x12uploadComputerInfo\x12\x36.greenness_track_toolkit.rpc.UploadComputerInfoRequest\x1a).greenness_track_toolkit.rpc.BaseResponse\x12k\n\x0cuploadStatus\x12\x30.greenness_track_toolkit.rpc.UploadStatusRequest\x1a).greenness_track_toolkit.rpc.BaseResponseB\x03\x90\x01\x01\x62\x06proto3')



_EIDREQUEST = DESCRIPTOR.message_types_by_name['EidRequest']
_UPLOADCOMPUTERINFOREQUEST = DESCRIPTOR.message_types_by_name['UploadComputerInfoRequest']
_EIDRESPONSE = DESCRIPTOR.message_types_by_name['EidResponse']
_UPLOADSTATUSREQUEST = DESCRIPTOR.message_types_by_name['UploadStatusRequest']
EidRequest = _reflection.GeneratedProtocolMessageType('EidRequest', (_message.Message,), {
  'DESCRIPTOR' : _EIDREQUEST,
  '__module__' : 'agent_info_service_pb2'
  # @@protoc_insertion_point(class_scope:greenness_track_toolkit.rpc.EidRequest)
  })
_sym_db.RegisterMessage(EidRequest)

UploadComputerInfoRequest = _reflection.GeneratedProtocolMessageType('UploadComputerInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADCOMPUTERINFOREQUEST,
  '__module__' : 'agent_info_service_pb2'
  # @@protoc_insertion_point(class_scope:greenness_track_toolkit.rpc.UploadComputerInfoRequest)
  })
_sym_db.RegisterMessage(UploadComputerInfoRequest)

EidResponse = _reflection.GeneratedProtocolMessageType('EidResponse', (_message.Message,), {
  'DESCRIPTOR' : _EIDRESPONSE,
  '__module__' : 'agent_info_service_pb2'
  # @@protoc_insertion_point(class_scope:greenness_track_toolkit.rpc.EidResponse)
  })
_sym_db.RegisterMessage(EidResponse)

UploadStatusRequest = _reflection.GeneratedProtocolMessageType('UploadStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADSTATUSREQUEST,
  '__module__' : 'agent_info_service_pb2'
  # @@protoc_insertion_point(class_scope:greenness_track_toolkit.rpc.UploadStatusRequest)
  })
_sym_db.RegisterMessage(UploadStatusRequest)

_AGENTINFOSERVICE = DESCRIPTOR.services_by_name['AgentInfoService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\220\001\001'
  _EIDREQUEST._serialized_start=71
  _EIDREQUEST._serialized_end=168
  _UPLOADCOMPUTERINFOREQUEST._serialized_start=171
  _UPLOADCOMPUTERINFOREQUEST._serialized_end=355
  _EIDRESPONSE._serialized_start=357
  _EIDRESPONSE._serialized_end=461
  _UPLOADSTATUSREQUEST._serialized_start=463
  _UPLOADSTATUSREQUEST._serialized_end=513
  _AGENTINFOSERVICE._serialized_start=516
  _AGENTINFOSERVICE._serialized_end=863
AgentInfoService = service_reflection.GeneratedServiceType('AgentInfoService', (_service.Service,), dict(
  DESCRIPTOR = _AGENTINFOSERVICE,
  __module__ = 'agent_info_service_pb2'
  ))

AgentInfoService_Stub = service_reflection.GeneratedServiceStubType('AgentInfoService_Stub', (AgentInfoService,), dict(
  DESCRIPTOR = _AGENTINFOSERVICE,
  __module__ = 'agent_info_service_pb2'
  ))


# @@protoc_insertion_point(module_scope)
