# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x1bgreenness_track_toolkit.rpc\"\\\n\x0c\x42\x61seResponse\x12;\n\nresultCode\x18\x01 \x01(\x0e\x32\'.greenness_track_toolkit.rpc.ResultCode\x12\x0f\n\x07message\x18\x02 \x01(\t*\x1f\n\nResultCode\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x62\x06proto3')

_RESULTCODE = DESCRIPTOR.enum_types_by_name['ResultCode']
ResultCode = enum_type_wrapper.EnumTypeWrapper(_RESULTCODE)
OK = 0
ERROR = 1


_BASERESPONSE = DESCRIPTOR.message_types_by_name['BaseResponse']
BaseResponse = _reflection.GeneratedProtocolMessageType('BaseResponse', (_message.Message,), {
  'DESCRIPTOR' : _BASERESPONSE,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:greenness_track_toolkit.rpc.BaseResponse)
  })
_sym_db.RegisterMessage(BaseResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESULTCODE._serialized_start=139
  _RESULTCODE._serialized_end=170
  _BASERESPONSE._serialized_start=45
  _BASERESPONSE._serialized_end=137
# @@protoc_insertion_point(module_scope)
