# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: emission_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import greenness_track_toolkit.rpc.common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x65mission_service.proto\x12\x1bgreenness_track_toolkit.rpc\x1a\x0c\x63ommon.proto\"w\n\x15InsertEmissionRequest\x12\x0b\n\x03\x65id\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_ip\x18\x02 \x01(\t\x12\x13\n\x0bupload_time\x18\x03 \x01(\t\x12\x0e\n\x06\x65nergy\x18\x04 \x01(\x02\x12\r\n\x05\x66lops\x18\x05 \x01(\x02\x12\x0b\n\x03\x63o2\x18\x06 \x01(\x02\x32\x86\x01\n\x0f\x45missionService\x12s\n\x12insertEmissionData\x12\x32.greenness_track_toolkit.rpc.InsertEmissionRequest\x1a).greenness_track_toolkit.rpc.BaseResponseb\x06proto3')



_INSERTEMISSIONREQUEST = DESCRIPTOR.message_types_by_name['InsertEmissionRequest']
InsertEmissionRequest = _reflection.GeneratedProtocolMessageType('InsertEmissionRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSERTEMISSIONREQUEST,
  '__module__' : 'emission_service_pb2'
  # @@protoc_insertion_point(class_scope:greenness_track_toolkit.rpc.InsertEmissionRequest)
  })
_sym_db.RegisterMessage(InsertEmissionRequest)

_EMISSIONSERVICE = DESCRIPTOR.services_by_name['EmissionService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSERTEMISSIONREQUEST._serialized_start=69
  _INSERTEMISSIONREQUEST._serialized_end=188
  _EMISSIONSERVICE._serialized_start=191
  _EMISSIONSERVICE._serialized_end=325
# @@protoc_insertion_point(module_scope)
